<?php
$clas = $con->query("select * from dp_atrib_classifica where funcid = ".$_REQUEST["idfunc"]);
$row = $clas->fetch(PDO::FETCH_ASSOC);
$turme = $con->query("SELECT dp_atrib_turma.turmaid, dp_atrib_turma.turmagrupo, dp_atrib_turma.turmanome, locais.nome as escola, locais.endereco, locais.numero, locais.bairro, locais.telefone1, dp_turnos.grupo as periodo, dp_turnos.nome as hora, dp_turnos.entrada, dp_turnos.saida, grupos.grupo FROM dp_atrib_turma , locais , dp_turnos , grupos WHERE dp_atrib_turma.turmalocal = locais.id and dp_atrib_turma.turmaperiodo = dp_turnos.id and dp_atrib_turma.turmagrupo = grupos.id and dp_atrib_turma.turmaid = ".$_REQUEST["turma"]);
$row1 = $turme->fetch(PDO::FETCH_ASSOC);
$subt = $con->query("SELECT dp_atrib_sub.*, locais.nome, locais.endereco, locais.numero, locais.bairro, locais.telefone1, dp_turnos.grupo, dp_turnos.nome as periodo, dp_turnos.entrada, dp_turnos.saida FROM dp_atrib_sub, locais, dp_turnos WHERE locais.id = dp_atrib_sub.sublocal and dp_turnos.id = dp_atrib_sub.subperiodo and dp_atrib_sub.subativo = 1 and dp_atrib_sub.turmaid = ".$_REQUEST["turma"]);
$row2 = $subt->fetchAll(PDO::FETCH_ASSOC);
$item = $con->query("SELECT dp_atrib_item.itemid, dp_atrib_item.hora, dp_atrib_item.itemstatus, dp_atrib_item.itemmotivo, dp_atrib_item.itemposicao, dp_funcionarios.nome, dp_funcionarios.codmatricula, dp_motivos.nome as motivo  FROM dp_atrib_item , dp_funcionarios , dp_motivos  WHERE dp_atrib_item.itemfunc = dp_funcionarios.id and dp_atrib_item.itemativo = 1 and dp_motivos.id = dp_atrib_item.itemmotivo and dp_atrib_item.turmaid = ".$_REQUEST["turma"]." order by itemposicao");
$row3 = $item->fetchAll(PDO::FETCH_ASSOC);
function limite($texto, $tamanho){
    $rest = substr($texto, 0, $tamanho);
    return iconv('utf-8','iso-8859-1', $rest);
}
$ordem = array('1' => 'Tilular', '2' => 'Suplente', '3' => '2º Suplente', '4' => '3º Suplente');
$dia = (int)date('d',time());
$mesi = date('m');
switch ($mesi){
case 1: $mes = "Janeiro"; break;
case 2: $mes = "Fevereiro"; break;
case 3: $mes = "Março"; break;
case 4: $mes = "Abril"; break;
case 5: $mes = "Maio"; break;
case 6: $mes = "Junho"; break;
case 7: $mes = "Julho"; break;
case 8: $mes = "Agosto"; break;
case 9: $mes = "Setembro"; break;
case 10: $mes = "Outubro"; break;
case 11: $mes = "Novembro"; break;
case 12: $mes = "Dezembro"; break;
}
$ano = (int)date('Y',time());
$hora = (int)date('G',time());
$min = (int)date('i',time());
$cabec = "Este documento deverá ser apresentado na nova Unidade Escolar no primeiro dia útil apóes a atribuição.";
$data = "Suzano/SP, ".$dia." de ".$mes." de ".$ano.".";
$pdf = new FPDF();
    $pdf->AddPage();
    $pdf->SetDrawColor(0,0,0);
    $pdf->SetFillColor(210,210,210);
    $pdf->SetFont('Arial','B',16);
    $pdf->Cell(0,10,iconv('UTF-8', 'ISO-8859-1//IGNORE', 'SECRETARIA MUNICIPAL DE EDUCAÇÃO DE SUZANO'),0,1,'C',false);        
    $pdf->SetFont('Arial','B',14);
    $pdf->Cell(0,10,iconv('UTF-8', 'ISO-8859-1//IGNORE', 'ENCAMINHAMENTO DE FUNCIONÁRIO À UNIDADE ESCOLAR'),0,1,'C',false);
    $pdf->SetFont('Arial','B',7);
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Mátricula'), 1,0,'C', true);
    $pdf->Cell(140, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Nome'), 1,0,'L', true);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Classificação'), 1,0,'C', true);
    $pdf->Ln();
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $row["matricula"]), 1,0,'C', false);
    $pdf->Cell(140, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row["nome"])), 1,0,'L', false);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $row["classifica"]."º"), 1,0,'C', false);
    $pdf->Ln();
    $pdf->SetFont('Arial','B',7);
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Turma'), 1,0,'C', true);
    $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Escola'), 1,0,'L', true);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'grupo'), 1,0,'C', true);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Turma'), 1,0,'C', true);
    $pdf->Cell(40, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Periodo'), 1,0,'C', true);
    $pdf->Ln();
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $row1["turmaid"]), 1,0,'C', false);
    $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row1["escola"])), 1,0,'L', false);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row1["grupo"])), 1,0,'C', false);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row1["grupo"]." ".$row1["turmanome"])), 1,0,'C', false);
    $pdf->Cell(40, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row1["periodo"]."-".$row1["hora"]."(".$row1["entrada"]."-".$row1["saida"].")")), 1,0,'C', false);
    if ($row1["turmagrupo"] == 21){
        $pdf->Ln();
        $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Local'), 1,0,'L', true);
        $pdf->Cell(40, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Periodo'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '1º Ano'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '2º Ano'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '3º Ano'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '4º Ano'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '5º Ano'), 1,0,'C', true);
        $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Horas de projeto'), 1,0,'C', true);
        $cor = false;
        $pdf->SetFillColor(190,190,190);
        foreach ($row2 as $ln) {            
            $pdf->Ln();
            $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($ln["nome"])), 1,0,'L', $cor);
            $pdf->Cell(40, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($ln["entrada"]."-".$ln["saida"])), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["a"]), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["b"]), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["c"]), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["d"]), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["e"]), 1,0,'C', $cor);
            $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["f"]), 1,0,'C', $cor);
            $cor = !$cor;
         }
    }
    $pdf->SetFillColor(210,210,210);
    $pdf->Ln();
    $pdf->Cell(190, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'histórico de atribuições'), 1,0,'C', true);
    $pdf->Ln();
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Matrícula'), 1,0,'C', true);
    $pdf->Cell(80, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Docente'), 1,0,'L', true);
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Atribuição'), 1,0,'C', true);
    $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Motivo'), 1,0,'C', true);
    $pdf->Ln();
    $cor = false;
        $pdf->SetFillColor(190,190,190);
        foreach ($row3 as $ln){
            $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["codmatricula"]), 1,0,'C', $cor);
            $pdf->Cell(80, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($ln["nome"])), 1,0,'L', $cor);
            $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ordem[$ln["itemposicao"]]), 1,0,'C', $cor);
            $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($ln["motivo"])), 1,0,'C', $cor);
            $pdf->Ln();
            $cor = !$cor;
        }
    $pdf->Ln();
    $pdf->Ln();
    $pdf->MultiCell(0,5,iconv('utf-8','iso-8859-1',$cabec),0,'C');
    $pdf->Ln();
    $pdf->MultiCell(0,5,iconv('utf-8','iso-8859-1',$data),0,'C');
    $pdf->Ln();
    $pdf->Ln();
    $pdf->Ln();
    $pdf->Cell(90, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row["nome"])), 'T',0,'C', false);
    $pdf->Cell(10, 5, '', 0,0,'C', false);
    $pdf->Cell(90, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Funcionario RH'), 'T',0,'C', false);
    $pdf->Ln();
    $pdf->Cell(190, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Atribuido em '.date('d/m/Y H:i:s', strtotime($row3[0]["hora"]))), 'T',0,'R', false);
//cópia
    $pdf->Ln();
    $pdf->Ln();
    $pdf->SetDrawColor(0,0,0);
    $pdf->SetFillColor(210,210,210);
    $pdf->SetFont('Arial','B',16);
    $pdf->Cell(0,10,iconv('UTF-8', 'ISO-8859-1//IGNORE', 'SECRETARIA MUNICIPAL DE EDUCAÇÃO DE SUZANO'),0,1,'C',false);        
    $pdf->SetFont('Arial','B',14);
    $pdf->Cell(0,10,iconv('UTF-8', 'ISO-8859-1//IGNORE', 'ENCAMINHAMENTO DE FUNCIONÁRIO À UNIDADE ESCOLAR'),0,1,'C',false);
    $pdf->SetFont('Arial','B',7);
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Mátricula'), 1,0,'C', true);
    $pdf->Cell(140, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Nome'), 1,0,'L', true);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Classificação'), 1,0,'C', true);
    $pdf->Ln();
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $row["matricula"]), 1,0,'C', false);
    $pdf->Cell(140, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row["nome"])), 1,0,'L', false);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $row["classifica"]."º"), 1,0,'C', false);
    $pdf->Ln();
    $pdf->SetFont('Arial','B',7);
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Turma'), 1,0,'C', true);
    $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Escola'), 1,0,'L', true);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'grupo'), 1,0,'C', true);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Turma'), 1,0,'C', true);
    $pdf->Cell(40, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Periodo'), 1,0,'C', true);
    $pdf->Ln();
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $row1["turmaid"]), 1,0,'C', false);
    $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row1["escola"])), 1,0,'L', false);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row1["grupo"])), 1,0,'C', false);
    $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row1["grupo"]." ".$row1["turmanome"])), 1,0,'C', false);
    $pdf->Cell(40, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row1["periodo"]."-".$row1["hora"]."(".$row1["entrada"]."-".$row1["saida"].")")), 1,0,'C', false);
    $pdf->Ln();
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Endereço:'), 1,0,'C', true);
    $pdf->Cell(140, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row1["endereco"].", ".$row1["numero"]." - ".$row1["bairro"])), 1,0,'L', false);
    $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Fone:'), 1,0,'C', true);
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $row1["telefone1"]), 1,0,'C', false);
    if ($row1["turmagrupo"] == 21){
        $pdf->Ln();
        $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Local'), 1,0,'L', true);
        $pdf->Cell(40, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Periodo'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '1º Ano'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '2º Ano'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '3º Ano'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '4º Ano'), 1,0,'C', true);
        $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', '5º Ano'), 1,0,'C', true);
        $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Horas de projeto'), 1,0,'C', true);
        $cor = false;
        $pdf->SetFillColor(190,190,190);
        foreach ($row2 as $ln) {            
            $pdf->Ln();
            $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($ln["nome"])), 1,0,'L', $cor);
            $pdf->Cell(40, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($ln["entrada"]."-".$ln["saida"])), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["a"]), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["b"]), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["c"]), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["d"]), 1,0,'C', $cor);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["e"]), 1,0,'C', $cor);
            $pdf->Cell(30, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["f"]), 1,0,'C', $cor);
            $cor = !$cor;
            $pdf->Ln();
            $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Endereço:'), 1,0,'C', true);
            $pdf->Cell(140, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($ln["endereco"].", ".$ln["numero"]." - ".$ln["bairro"])), 1,0,'L', false);
            $pdf->Cell(10, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Fone:'), 1,0,'C', true);
            $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["telefone1"]), 1,0,'C', false);
         }
    }
    $pdf->SetFillColor(210,210,210);
    $pdf->Ln();
    $pdf->Cell(190, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'histórico de atribuições'), 1,0,'C', true);
    $pdf->Ln();
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Matrícula'), 1,0,'C', true);
    $pdf->Cell(80, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Docente'), 1,0,'L', true);
    $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Atribuição'), 1,0,'C', true);
    $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Motivo'), 1,0,'C', true);
    $pdf->Ln();
    $cor = false;
        $pdf->SetFillColor(190,190,190);
        foreach ($row3 as $ln){
            $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ln["codmatricula"]), 1,0,'C', $cor);
            $pdf->Cell(80, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($ln["nome"])), 1,0,'L', $cor);
            $pdf->Cell(20, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', $ordem[$ln["itemposicao"]]), 1,0,'C', $cor);
            $pdf->Cell(70, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($ln["motivo"])), 1,0,'C', $cor);
            $pdf->Ln();
            $cor = !$cor;
        }
    $pdf->Ln();
    $pdf->Ln();
    $pdf->MultiCell(0,5,iconv('utf-8','iso-8859-1',$cabec),0,'C');
    $pdf->Ln();
    $pdf->MultiCell(0,5,iconv('utf-8','iso-8859-1',$data),0,'C');
    $pdf->Ln();
    $pdf->Ln();
    $pdf->Ln();
    $pdf->Cell(90, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', utf8_encode($row["nome"])), 'T',0,'C', false);
    $pdf->Cell(10, 5, '', 0,0,'C', false);
    $pdf->Cell(90, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Funcionario RH'), 'T',0,'C', false);
    $pdf->Ln();
    $pdf->Cell(190, 5, iconv('UTF-8', 'ISO-8859-1//IGNORE', 'Atribuido em '.date('d/m/Y H:i:s', strtotime($row3[0]["hora"]))), 'T',0,'R', false);
$pdf->Output();
?>